### ISSUE TITLE
if I change the teacher model  to a much smaller one like mobilenet, will the distill works too?

### ISSUE THREAD

**Issue by leonardodora** [mit-han-lab/gan-compression#10]
hi!
I noticed that your distill process only support resnet, so I want to know would smaller teacher model work.

**Comment by lmxyy** [comment]
Sorry, I do not quite understand your question. Currently, our codebase only supports ResNet generator because the generators in pix2pix and CycleGAN are in ResNet architecture (on pix2pix, we observe that the ResNet generator is better than the UNet generator, refer to 
Network architecture for pix2pix in [Appendix 6.2](https://arxiv.org/pdf/2003.08936.pdf)). We do not modify the backbone of the original generator.

**Comment by leonardodora** [comment]
> Sorry, I do not quite understand your question. Currently, our codebase only supports ResNet generator because the generators in pix2pix and CycleGAN are in ResNet architecture (on pix2pix, we observe that the ResNet generator is better than the UNet generator, refer to
> Network architecture for pix2pix in [Appendix 6.2](https://arxiv.org/pdf/2003.08936.pdf)). We do not modify the backbone of the original generator.

thanks for your reply!
I want to know your code base is compatible with different architecture. That is if  I train my teacher model on mobilenet or unet  instead of  resnet, would the distill work.

**Comment by lmxyy** [comment]
I think the distillation will work, but you may need to add some codes to specify the distillation layers for the mobilenet or unet architecture.

**Comment by junyanz** [comment]
I think the `mapping_layers` defines the distillation layers (see this [line](https://github.com/mit-han-lab/gan-compression/blob/master/distillers/base_resnet_distiller.py#L100)).  We should try to make it as a flag and make it also applicable to other architectures.

**Comment by leonardodora** [comment]
thx for your reply!!
btw, I should run distill.py then train_supernet.py , or I just run train_supernet.py after training the teacher model. And what is the difference between the two process. 

> I think the distillation will work, but you may need to add some codes to specify the distillation layers for the mobilenet or unet architecture.

**Comment by lmxyy** [comment]
> thx for your reply!!
> btw, I should run distill.py then train_supernet.py , or I just run train_supernet.py after training the teacher model. And what is the difference between the two process.
> 
> > I think the distillation will work, but you may need to add some codes to specify the distillation layers for the mobilenet or unet architecture.

If you need to reproduce our results, you may need to run [distill.py](https://github.com/mit-han-lab/gan-compression/blob/master/distill.py) then [train_supernet.py](https://github.com/mit-han-lab/gan-compression/blob/master/train_supernet.py). The [distill.py](https://github.com/mit-han-lab/gan-compression/blob/master/distill.py) can make the model compact before the "once-for-all" network training.
As a matter of fact, you could directly run [train_supernet.py](https://github.com/mit-han-lab/gan-compression/blob/master/train_supernet.py) after training a teacher model if you change the candidate subnet set in [resnet_configs](https://github.com/mit-han-lab/gan-compression/blob/master/configs/resnet_configs.py). We will release a lite pipeline later which will skip the distillation process.
