### ISSUE TITLE
distilling on higer resolution

### ISSUE THREAD

**Issue by youjinChung** [mit-han-lab/gan-compression#105]
Hello,
I am training a CycleGAN with a [repo](https://github.com/snap-research/CAT) based on this paper.
I found distilling on 256x256 works fine and very well but not on 512x512.
[This is my thread about it.](https://github.com/snap-research/CAT/issues/27)
I found this repo very recently, so was thinking of investigating the paper and repo, but posting this question first to get any hints for distilling.
Are there any ways to prevent collapsing with fine-tuning? or should I change the student structure?

**Comment by lmxyy** [comment]
What student architecture did you use?
