### ISSUE TITLE
"Once-for-all" Network Training Problem

### ISSUE THREAD

**Issue by saijo0404** [mit-han-lab/gan-compression#108]
```
#!/usr/bin/env bash
python train_supernet.py --dataroot database/edges2shoes-r \
  --supernet resnet \
  --log_dir logs/pix2pix/edges2shoes-r/supernet \
  --batch_size 4 \
  --restore_teacher_G_path logs/pix2pix/edges2shoes-r/train/checkpoints/latest_net_G.pth \
  --restore_student_G_path logs/pix2pix/edges2shoes-r/distill/checkpoints/latest_net_G.pth \
  --restore_D_path logs/pix2pix/edges2shoes-r/distill/checkpoints/latest_net_D.pth \
  --real_stat_path real_stat/edges2shoes-r_B.npz \
  --nepochs 10 --nepochs_decay 30 \
  --teacher_ngf 64 --student_ngf 48 \
  --config_set channels-48 --meta_path datasets/metas/edges2shoes-r/train1.meta \
    --teacher_netG resnet_9blocks \
  --student_netG 
```
Hello, I used this bash to training  "Once-for-all" Network, but I don't know what is there in the parameter --student_netG that I can use?
My restore_teacher_G, restore_student_G and restore_D_path are use resnet_9blocks.

**Comment by lmxyy** [comment]
Hi, the `student_netG` should be a supernet architecture. Currently, we only support `super_mobile_resnet_9blocks`. So I guess what you could do is follow the [Fast GAN Compression tutorial](https://github.com/mit-han-lab/gan-compression/blob/master/docs/tutorials/fast_gan_compression.md) to directly use the `resnet_9blocks` teacher to train a ``super_mobile_resnet_9blocks` once-for-all network, or train a `mobile_resnet_9blocks` mobile teacher (or use our pre-trained one) and redistill a `mobile_resnet_9blocks` student. I suggest the first one.

**Comment by saijo0404** [comment]
ok, thank you so much. I try do this.
