### ISSUE TITLE
Is it possible used in stylegan2?

### ISSUE THREAD

**Issue by GitHubZiqiangZhou** [mit-han-lab/gan-compression#11]
Great work!
Is it possible used in stylegan2?
If it is possible, how to use it?Can you give me some tips?
Thanks a lot!

**Comment by lmxyy** [comment]
I think it is possible. Currently, we are trying to compress StyleGANv2 with our codebase. 
Once finishing the compression, we will release the code and compressed models.

**Comment by GitHubZiqiangZhou** [comment]
Excellent!
I look forward to your results.
I am your fan, Thank you！

**Comment by ak9250** [comment]
@lmxyy hi is there any update on compressed styleganv2 thanks

**Comment by junyanz** [comment]
We are currently working on a lighter and training pipeline at this moment. Stylegan2 is on our list, but it may not be ready for the near future.
