### ISSUE TITLE
Cannot access to https://hanlab.mit.edu/

### ISSUE THREAD

**Issue by GasaiYU** [mit-han-lab/gan-compression#115]
I cannot get access to https://hanlab.mit.edu/, which prevents me getting some statistical information and datasets.

**Comment by lmxyy** [comment]
The URL should work. You need to input the entire URL into your browser to access the statistics (e.g., https://hanlab.mit.edu/files/gan_compression/real_stat/edges2shoes-r_B.npz). If this still does not work, you can follow the instructions [here](https://github.com/mit-han-lab/gan-compression#fid-computation) to extract the statistics from your dataset.
