### ISSUE TITLE
ERROR 403: Forbidden

### ISSUE THREAD

**Issue by sr1dh4r** [mit-han-lab/gan-compression#116]
Getting a 403 forbidden error when trying to download datasets, stats, pre-trained model.

Tried to following the **training** section (
https://github.com/mit-han-lab/gan-compression/blob/master/docs/tutorials/gan_compression.md)
but unable to proceed.

I tried to download dataset from kaggle and train the model but get the following errors on running 
"bash scripts/cycle_gan/horse2zebra/train_mobile.sh"

**AssertionError: database/horse2zebra/valA is not a valid directory**

After the following commands
mkdir -p database/horse2zebra/valA
mkdir -p database/horse2zebra/valB

I get the following error 
**FileNotFoundError: [Errno 2] No such file or directory: 'real_stat/horse2zebra_A.npz'**

Trying to generate stats and get the following error
python get_real_stat.py --dataroot database/horse2zebra/trainA/ --output_path real_stat/horse2zebra_A.npz --direction AtoB

"AssertionError: database/horse2zebra/trainA/val is not a valid directory"

**Comment by lmxyy** [comment]
Sorry for the inconvenience. 
We are currently updating our website and migrating data. I will let you know when it is done (within one day).

**Comment by lmxyy** [comment]
The URLs are updated. Could you try again?

**Comment by sr1dh4r** [comment]
Thanks for looking into this but I am still facing the same issues with a fresh checkout.

**$ bash datasets/download_cyclegan_dataset.sh horse2zebra**
Specified [horse2zebra]
WARNING: timestamping does nothing in combination with -O. See the manual
for details.

--2023-10-01 16:12:54--  https://people.eecs.berkeley.edu/~taesung_park/CycleGAN/datasets/horse2zebra.zip
Resolving people.eecs.berkeley.edu (people.eecs.berkeley.edu)... 128.32.244.190
Connecting to people.eecs.berkeley.edu (people.eecs.berkeley.edu)|128.32.244.190|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-10-01 16:12:56 ERROR 403: Forbidden.

Archive:  ./database/horse2zebra.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of ./database/horse2zebra.zip or
        ./database/horse2zebra.zip.zip, and cannot find ./database/horse2zebra.zip.ZIP, period.

**Comment by lmxyy** [comment]
For the CycleGAN datasets, we used the URL from the original repo [junyanz/pytorch-CycleGAN-and-pix2pix](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix). It seems that they also updated the URLs. I have updated ours correspondingly. Can you try again?

**Comment by sr1dh4r** [comment]
Thank you !! I'm able to download the assets and run the test scripts (horse2zebra ones) now.
