### ISSUE TITLE
Request for Access to Pretrained Model for Verification and Replication Purposes.

### ISSUE THREAD

**Issue by BigBooks** [mit-han-lab/gan-compression#117]
The original link to the MIT server, https://hanlab.mit.edu/files/gan_compression/, appears to be no longer active or valid.
Can you resend a valid link?
Thank you for your time and consideration.

**Comment by lmxyy** [comment]
Sorry for the late reply. I missed your issue. Previously we have migrated the URL to hanlab18.mit.edu as said in #116 . Are you able to download the models and dataset now?

**Comment by lmxyy** [comment]
The URL link is updated. You can try again with the latest repo.

**Comment by BigBooks** [comment]
Thank you very much for your help.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mit-han-lab/gan-compression"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月6日(星期四) 上午6:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mit-han-lab/gan-compression] Request for Access to Pretrained Model for Verification and Replication Purposes. (Issue #117)





 
The URL link is updated. You can try again with the latest repo.
