### ISSUE TITLE
URL is not supported

### ISSUE THREAD

**Issue by lixiaoyu0429** [mit-han-lab/gan-compression#118]
Hello, when I try to download the pre-trained model using python scripts/download_model.py, the URL https://hanlab18.mit.edu/files/gan_compression/ is no longer valid. Is there a new URL available?

**Comment by lmxyy** [comment]
Seems the server is down. We are working on it. I will let you know when it is back.

**Comment by lixiaoyu0429** [comment]
Hello, thank you very much for your response. However, the school's server repair is expected to be slow. Could you please temporarily share it on Google Drive or another platform?

**Comment by lmxyy** [comment]
Which specific checkpoint do you want?

**Comment by lmxyy** [comment]
I've got the data back. I will update the link so that you should be able to download it tomorrow.

**Comment by lixiaoyu0429** [comment]
Thank you for patiently answering the question

**Comment by lmxyy** [comment]
you can find all the assets in our [huggingface repo](https://huggingface.co/mit-han-lab/gan-compression/tree/main). I will update the script for downloading them later.
