### ISSUE TITLE
Does OFA training reduce the capacity gap between student and teacher?

### ISSUE THREAD

**Issue by MarSaKi** [mit-han-lab/gan-compression#15]
I compare the distill result and the supernet result(w/o finetune), results are:

#super net w/o finetune:
config_str                               MACs     FID
32_32_32_32_32_32_32_32  4.955     55.73
32_16_32_24_32_32_24_24  3.639     60.27
16_16_32_16_32_32_16_16     2.546      65.33
16_16_16_32_32_32_16_24    1.977       134.45
16_16_16_16_16_16_16_16        1.421       223.46

#distill
config_str                               MACs     FID
32_32_32_32_32_32_32_32  4.955     65.78
32_16_32_24_32_32_24_24  3.639     73.50
16_16_32_16_32_32_16_16      2.546     80.36
16_16_16_32_32_32_16_24     1.977      83.06
16_16_16_16_16_16_16_16        1.421      103.17

it seems when MACs>1.977, supernet is better than distill, but when MACs<1.977, distill is better.
Also it seems when MACs>1.977, OFA training reduce the capacity gpa between student and teacher, then get better performance.
Do you know why?

**Comment by lmxyy** [comment]
When training a "once-for-all" network, **all candidate subnets** are training together via weight sharing. Therefore, sometimes the small networks after the "once-for-all" training may not perform as well as the distillation. 
For the big subnets, "once-for-all" training may bring extra benefits for them so sometimes they could outperform the distillation. Similar phenomena have been found in [Cai *et al*](https://arxiv.org/pdf/1908.09791.pdf).

**Comment by MarSaKi** [comment]
Thanks for your reply
