### ISSUE TITLE
Motivation behind dropping spectral normalization in GauGAN?

### ISSUE THREAD

**Issue by s1ddok** [mit-han-lab/gan-compression#16]
I noticed you removed spectral normalization in GauGAN generators. Is there a particular motivation behind this?

**Comment by lmxyy** [comment]
Yes. During our experiments, we found the spectral normalization didn't make big differences (which is also reported in [GauGAN Paper](https://arxiv.org/pdf/1903.07291.pdf), see Table 5). Besides, it is not easy to add spectral normalization to SeperableConv. So we remove the spectral normalization in our following experiments.

**Comment by s1ddok** [comment]
Thanks for the answer!
