### ISSUE TITLE
hanlab website down?

### ISSUE THREAD

**Issue by thesiti92** [mit-han-lab/gan-compression#17]
i'm trying to download your pretrained models and it seems that the fileserver is down. Can you guys check it out?

**Comment by lmxyy** [comment]
Yes. It seems that our server is down and currently we have no idea when it can be fixed.
We will upload our models and datasets on google drive or dropbox. Once we have uploaded, we will inform you.

**Comment by lmxyy** [comment]
I've uploaded our pretrained models on [googledrive](https://drive.google.com/drive/folders/1u6O652AReSi0z5LC7vgVwnwkQYRPrDWl?usp=sharing).

**Comment by tonylins** [comment]
Hi, the hanlab website is now online. Sorry for the waiting.
