### ISSUE TITLE
What kind of model compression can be used in the method proposed in the paper?

### ISSUE THREAD

**Issue by jiaying96** [mit-han-lab/gan-compression#18]
Is it possible used in any GAN-based model?
such as : https://github.com/HsinYingLee/DRIT and https://github.com/NVlabs/FUNIT

**Comment by lmxyy** [comment]
Yes. GAN Compression is a general-purpose method for compressing conditional GANs.

**Comment by deepseek** [comment]
@lmxyy Does this include stylegan2?
