### ISSUE TITLE
How to run StyleGAN experiments?

### ISSUE THREAD

**Issue by zhengzhe97** [mit-han-lab/gan-compression#2]

**Comment by zhengzhe97** [comment]
How to train using the code? Can give some instruction about training?

**Comment by junyanz** [comment]
StyleGAN was not included in the paper. Training instruction will be added later.

**Comment by anguoyang** [comment]
@junyanz how about StyleGAN so far?

**Comment by lmxyy** [comment]
We do not support StyleGAN for now. Maybe you could check [mit-han-lab/anycost-gan](https://github.com/mit-han-lab/anycost-gan) for it.
