### ISSUE TITLE
Do I have to use the statistics during training the teacher net?

### ISSUE THREAD

**Issue by acoder-fin** [mit-han-lab/gan-compression#20]
I trained a cycleGAN model without using the statistical information ofthe groud-truth images (using the original cycleGAN code). Is it possible to make the statistical information up to the model trained using origial cycleGAN or I have to re-train the model using the new version?
Thanks.

**Comment by lmxyy** [comment]
The statistical information is just used for evaluation, which doesn't involve in the model training. So you do not have to retrain the model. Just evaluate the model with new statistical information is OK.
