### ISSUE TITLE
Why the FID results I got is different from the results in your paper?

### ISSUE THREAD

**Issue by zhuzm0902** [mit-han-lab/gan-compression#21]
Hi, I follow the instructions in Pix2pix Model Compression "bash scripts/pix2pix/edges2shoes-r/train_mobile.sh", but the model I got only got 28.79 on FID score which is different from the results in  your paper. Is there anything I forgot to do?

**Comment by lmxyy** [comment]
Could you please provide the best FID you've got in your log? The FID is sometimes unstable, I think your could set up a new run with a different seed.

**Comment by zhuzm0902** [comment]
The results in the log.txt is:
"
End of epoch 20 / 20 	 Time Taken: 2441.05 sec
###(Evaluate epoch: 20, iters: 239901, time: 83.268) fid: 28.786 fid-mean: 28.266 fid-best: 27.372 
Saving the model at the end of epoch 20, iters 239901
learning rate = 0.0000000
"
I will run again with a different seed to see the results. Thank you!

**Comment by lmxyy** [comment]
Hello, did you get the same result? If you did, I would close this issue.
