### ISSUE TITLE
About the different between "pruning + distill" and "GAN Compression" method.

### ISSUE THREAD

**Issue by nobodypengium** [mit-han-lab/gan-compression#23]
As mentioned in your paper (Appendix 6.1)

> we first train a MobileNet [25] style network from scratch, and then use the network as a teacher model to distill a smaller student network.

I guess "use the network as a teacher model to distill a smaller student network." corresponding to "Pre-distillation (Optional)..." [here](https://github.com/mit-han-lab/gan-compression/blob/master/docs/training_tutorial.md#pre-distillation) in your docs/training_tutorial.md.

And you have compared "Pruning + distill" to the "GAN Compression" method in 4.3 Figure 6.

My questions are:
1. Is it true that, in Figure 6, the "pruning + distill" network is the student network after "[Pre-distillation (Optional)...](https://github.com/mit-han-lab/gan-compression/blob/master/docs/training_tutorial.md#pre-distillation)" and the "GAN compression" is the network after NAS and fine-tuning.
2. Is is true that the student network is smaller than the teacher network because using the pruning method? And if so, what is the pruning method applied before training a once-for-all network?
3. What is the relationshap between Figure 3 ① and the pipline mentioned in Appendix 6.1? It seems that in Figure 3 ①, no purning method is applied.
![image](https://user-images.githubusercontent.com/13833330/83097196-15f65000-a0da-11ea-84db-2c3ba0c8406a.png)

Hope for your reply.

**Comment by lmxyy** [comment]
1. Yes, you are right.
2. We adopt the naive pruning method before NAS. For each convolution, we just sort the channels by their L1 norm and select the largest ones. You could refer to [weight_transfer.py](https://github.com/mit-han-lab/gan-compression/blob/94271976c6b0d2d8cb25379998c712349278371b/utils/weight_transfer.py#L107) for more details. We select the largest several channels of the pre-trained model and transfer the corresponding weights to the student model, which is the same as pruning.
3. The "once-for-all" student generator loads the weights of the pre-trained pruned student network. We only show the process of how to train a "once-for-all" network, so no pruning method is applied.

**Comment by nobodypengium** [comment]
Thanks for your quick reply!
