### ISSUE TITLE
Can the sharpness of the image be increased a little

### ISSUE THREAD

**Issue by goodclass** [mit-han-lab/gan-compression#24]
First of all, this is a subversive technical paper, which makes the reasoning model of mobile devices possible. If the picture definition is improved a little more, the breakdown threshold can be achieved.

- **This is a cartoon**
>![png](https://github.com/goodclass/PythonAI/blob/master/gcom/cart.jpg?raw=true)
- **It's aging**
>![png](https://github.com/goodclass/PythonAI/blob/master/gcom/old.jpg?raw=true)
- **This is mosaic**
>![png](https://github.com/goodclass/PythonAI/blob/master/gcom/mask.jpg?raw=true)

on the left, middle and right, real_ A，fake_ B，real_B
The cartoon picture is simple, but it's OK. Others may need to be improved.
I'm focusing on pix2pixhd and partialconv. The calculation amount and capacity of the model are relatively large. I wonder if I can refine the advantages to solve the problem.

- **Currently, reasoning data on mobile phones**, At iPhone 11pro speed, 256px is about 4 / s.I think there will be more than a dozen iPhone 12.
>>>![png](https://github.com/goodclass/PythonAI/blob/master/gcom/mobile.jpg?raw=true)

**Comment by ak9250** [comment]
have you tried upscaling afterwards?

**Comment by goodclass** [comment]
I'm trying
1K samples of the results on the screenshot
Now I'm sorting out more than 10k samples, and the training results can take a little time.
In the case of 512x512 large samples, observe the clarity again.
