### ISSUE TITLE
How do I compress the other GAN models

### ISSUE THREAD

**Issue by ypw1996** [mit-han-lab/gan-compression#25]
Hello, I want to use this method to compress the other GAN models, like starGAN, styleGAN. If it is feasible, What should I do?

**Comment by jiaying96** [comment]
+1，which part should be modified to compress the other GAN models

**Comment by lmxyy** [comment]
There are several parts you may need to modify.
* [data/](https://github.com/mit-han-lab/gan-compression/tree/master/data). You need to customize your dataset in this folder.
* [models/modules](https://github.com/mit-han-lab/gan-compression/tree/master/models/modules/). You need to define your generator and discriminator pytorch modules here.
* [configs/](https://github.com/mit-han-lab/gan-compression/tree/master/configs). You need to define a searching space here.
* [supernets/](https://github.com/mit-han-lab/gan-compression/tree/master/supernets). You need to create a "once-for-all" network trainer here. Specifically, you need to choose the matching layers and implement the training logic.

**Comment by junyanz** [comment]
Might worth writing a tutorial on compressing other gans models.

**Comment by deepseek** [comment]
@lmxyy compressing stylegan2 , then applying PULSE on top of that :sunglasses:

**Comment by AnimationFan** [comment]
It's true that this repository has no enough guide to show how to distill other model
