### ISSUE TITLE
Why GauGan compression does not inherit teacher's D?

### ISSUE THREAD

**Issue by s1ddok** [mit-han-lab/gan-compression#26]
In paper you mentioned that you inherit discriminator from pretrained teacher. I see that in GauGan compression you do not do that. am I correct?

**Comment by lmxyy** [comment]
Nope. We do inherit the discriminator in GauGAN. As you could see in [distill.sh](https://github.com/mit-han-lab/gan-compression/blob/dfc92e0b45c158b6d9567ea8bbc2fa9a50a40dda/scripts/gaugan/cityscapes/distill.sh#L7), we have restored a discriminator with argument `--restore_D_path`.

**Comment by s1ddok** [comment]
@lmxyy thanks for clarification! I just noticed that hey have different path prefixes and thought that it is path for student discriminator checkpointing.
