### ISSUE TITLE
multi-gpu

### ISSUE THREAD

**Issue by EliteBeastSlamor** [mit-han-lab/gan-compression#27]
How can I use multi-gpu when training?
I have tried --gpu_ids 1,2,3,4 when training, but when training mobile this can run correctly but when distilling this was not.

**Comment by lmxyy** [comment]
What distiller are you using? I didn't check the multi-gpu support for the Resnet distiller. I will fix it later.

**Comment by EliteBeastSlamor** [comment]
Thanks for concerning my issue. I had tried to use multi-gpu when distilling and have success doing so. Good code!
 we can just make --gpu_ids 1,2,3,4 and meanwhile make Tact.cuda() and Sact.cuda() to distill by 4 gpus!

**Comment by lmxyy** [comment]
I see. I have tried so and found there were no errors for double-gpu distilling even without `Tact.cuda()` and `Sact.cuda()`. I will close this issue. If you have other problem, you could open a new issue.
