### ISSUE TITLE
How to train the compressed model?

### ISSUE THREAD

**Issue by hhuyujie** [mit-han-lab/gan-compression#3]
Could you give me some instructions about how to train the compressed model, not the pre-trained compressed model? How about to take pix2pix for example? I don't understand those train mode.

**Comment by lmxyy** [comment]
We will add a tutorial for training later.

**Comment by leonardodora** [comment]
> We will add a tutorial for training later.

i want the tutorial too!!! looking forwards to that!!!

**Comment by lmxyy** [comment]
Our [training tutorial](https://github.com/mit-han-lab/gan-compression/blob/master/docs/training_tutorial.md) is released. You could follow the instructions in the tutorial to reproduce our compression results on pix2pix and cycleGAN. You could also have a look at our [overview](https://github.com/mit-han-lab/gan-compression/blob/master/docs/overview.md) for better understanding our codebase. 
If you have any other questions, you could open another issue.

**Comment by leonardodora** [comment]
> Our [training tutorial](https://github.com/mit-han-lab/gan-compression/blob/master/docs/training_tutorial.md) is released. You could follow the instructions in the tutorial to reproduce our compression results on pix2pix and cycleGAN. You could also have a look at our [overview](https://github.com/mit-han-lab/gan-compression/blob/master/docs/overview.md) for better understanding our codebase.
> I will close the issue later. If you have any other questions, you could open another issue.

thx!
