### ISSUE TITLE
other datasets

### ISSUE THREAD

**Issue by EliteBeastSlamor** [mit-han-lab/gan-compression#30]
Hi, author！
How can I transfer Pix2Pix model to my own datasets such as deRain datasets?
Can I just prepare the dataset according to the form like your datasets?

**Comment by lmxyy** [comment]
Of course, you can. I think you could just use modify our [aligned_dataset.py](https://github.com/mit-han-lab/gan-compression/blob/master/data/aligned_dataset.py) and arrange your dataset folder like ours.
To compute the FID score, you may need to split the dataset and use the script [get_real_stat.py](https://github.com/mit-han-lab/gan-compression/blob/master/get_real_stat.py) to get the real statistics of the validation set (see our [README](https://github.com/mit-han-lab/gan-compression#fid-computation)).

**Comment by EliteBeastSlamor** [comment]
Thanks for your answering. I have noticed that dataset proposed in the paper(like edges2shoes) are all in the form of Stitched pictures, which means styleA and styleB are concatenated. 

so when I use deRain dataset, Should I also make the data set into a corresponding format?

**Comment by lmxyy** [comment]
You could concatenate the styleA and styleB images with the script [combine_A_and_B.py](https://github.com/mit-han-lab/gan-compression/blob/master/datasets/combine_A_and_B.py]). 
Also, you could modify [aligned_dataset.py](https://github.com/mit-han-lab/gan-compression/blob/master/data/aligned_dataset.py) the dataset to support the non-stitched images.
