### ISSUE TITLE
Is Pre-distillation a required step?

### ISSUE THREAD

**Issue by pkhigh** [mit-han-lab/gan-compression#31]
I want to know the purpose of pre-distillation in the GAN-compression pipeline. How does it improve the pruning pipeline?  It is not mentioned anywhere in the paper.

**Comment by lmxyy** [comment]
Nope. We just used pre-distillation to narrow the search space in our paper. We have also ready released a pipeline without the pre-distillation (GAN Compression Lite). Please check [lite_pipeline.md](https://github.com/mit-han-lab/gan-compression/blob/master/docs/lite_pipeline.md) for more details.

**Comment by pkhigh** [comment]
The lite_pipeline is also divided into 2 stages. Can you explain what is happening in stage 1?

#!/usr/bin/env bash
python train_supernet.py --dataroot database/edges2shoes-r \
  --supernet resnet \
  --log_dir logs/pix2pix/edges2shoes-r_lite/supernet-stage1 \
  --batch_size 4 \
  --restore_teacher_G_path logs/pix2pix/edges2shoes-r_lite/mobile/checkpoints/latest_net_G.pth \
  --restore_student_G_path logs/pix2pix/edges2shoes-r_lite/mobile/checkpoints/latest_net_G.pth \
  --restore_D_path logs/pix2pix/edges2shoes-r_lite/mobile/checkpoints/latest_net_G.pth \
  --real_stat_path real_stat/edges2shoes-r_B.npz \
  --nepochs 2 --nepochs_decay 8 \
  --teacher_ngf 64 --student_ngf 64 \
  --config_set channels-64-pix2pix-stage1 --sort_channels

python train_supernet.py --dataroot database/edges2shoes-r \
  --supernet resnet \
  --log_dir logs/pix2pix/edges2shoes-r_lite/supernet-stage2 \
  --batch_size 4 \
  --restore_teacher_G_path logs/pix2pix/edges2shoes-r_lite/mobile/checkpoints/latest_net_G.pth \
  --restore_student_G_path logs/pix2pix/edges2shoes-r_lite/supernet-stage1/checkpoints/latest_net_G.pth \
  --restore_D_path logs/pix2pix/edges2shoes-r_lite/supernet-stage1/checkpoints/latest_net_G.pth \
  --real_stat_path real_stat/edges2shoes-r_B.npz \
  --nepochs 10 --nepochs_decay 30 \
  --teacher_ngf 64 --student_ngf 64 \
  --config_set channels-64-pix2pix

**Comment by lmxyy** [comment]
Both stages are for "once-for-all" training. 

In this stage, we applied a technique called "progressive searching", which means we enlarge the search space progressively. The search space of the first stage is all included in that of the second stage. 

The technique could help the "once-for-all" network training (as reported in [Cai et.al.](https://arxiv.org/pdf/1908.09791.pdf)) and is expected to be added into our ArXiv v3.

It is also okay to conduct single-stage "once-for-all" training, which means no "progressive searching". In my experiment, the performance of single-stage "once-for-all" training is as good as the result in the Table 1 in our paper for this edge2shoes dataset. Just input the following command:
```bash
python train_supernet.py --dataroot database/edges2shoes-r
--supernet resnet
--log_dir logs/pix2pix/edges2shoes-r_lite/supernet
--batch_size 4
--restore_teacher_G_path logs/pix2pix/edges2shoes-r_lite/mobile/checkpoints/latest_net_G.pth
--restore_student_G_path logs/pix2pix/edges2shoes-r_lite/mobile/checkpoints/latest_net_G.pth
--restore_D_path logs/pix2pix/edges2shoes-r_lite/mobile/checkpoints/latest_net_G.pth
--real_stat_path real_stat/edges2shoes-r_B.npz
--nepochs 10 --nepochs_decay 30
--teacher_ngf 64 --student_ngf 64
--config_set channels-64-pix2pix --sort_channels
```

**Comment by lmxyy** [comment]
Do you have other questions? If not, I will close the issue.

**Comment by pkhigh** [comment]
Thank you for the help. I don't have any questions for now.
