### ISSUE TITLE
Pix2PixHD

### ISSUE THREAD

**Issue by deepseek** [mit-han-lab/gan-compression#32]
@lmxyy @junyanz 
Did you conduct any test on compressing Pix2PixHD
Will other types of GANs be implemented in this repo

**Comment by lmxyy** [comment]
We didn't try our model on pix2pixHD, but I think it will work too.

**Comment by deepseek** [comment]
@lmxyy what is next for this repository?
which method you will implement here to compress? stylegan2, pix2pixhd?
what is the next step?

**Comment by junyanz** [comment]
We are currently working on a lighter and training pipeline at this moment (saving training time by 2-3x). StyleGAN2 and pix2pixHD are on our list, but it may not be ready for the near future. Feel free to try it by yourself.

**Comment by deepseek** [comment]
good luck
