### ISSUE TITLE
get_real_stat.py error

### ISSUE THREAD

**Issue by deepseek** [mit-han-lab/gan-compression#35]
@lmxyy 
i am trying everything from scratch, when running `get_real_stat.py` i get an error.
why does it require creating a `val` folder? there is already `valA` and `valB`

```
(gan) home@home-lnx:~/programs/level 2/gan-compression$ python get_real_stat.py --dataroot database/horse2zebra/ --output_path real_stat/horse2zebra_B.npz --direction AtoB
Traceback (most recent call last):
  File "get_real_stat.py", line 84, in <module>
    main(opt)
  File "get_real_stat.py", line 15, in main
    dataloader = create_dataloader(opt)
  File "/home/home/programs/level 2/gan-compression/data/__init__.py", line 45, in create_dataloader
    dataloader = CustomDatasetDataLoader(opt, verbose)
  File "/home/home/programs/level 2/gan-compression/data/__init__.py", line 97, in __init__
    self.dataset = dataset_class(opt)
  File "/home/home/programs/level 2/gan-compression/data/aligned_dataset.py", line 24, in __init__
    self.AB_paths = sorted(make_dataset(self.dir_AB))  # get image paths
  File "/home/home/programs/level 2/gan-compression/data/image_folder.py", line 45, in make_dataset
    assert os.path.isdir(dir) or os.path.islink(dir), '%s is not a valid directory' % dir
AssertionError: database/horse2zebra/val is not a valid directory
```

```
(gan) home@home-lnx:~/programs/level 2/gan-compression/database/horse2zebra$ tree -d
.
├── testA
├── testB
├── trainA
├── trainB
├── valA -> testA
└── valB -> testB
```

**Comment by lmxyy** [comment]
For the horse2zebra, we do not have aligned data. So you may need to specify the dataset mode with argument `--dataset_mode single`. The whole command may be like this
```bash
python get_real_stat.py --dataroot database/horse2zebra/valB --output_path real_stat/horse2zebra_B.npz --direction AtoB --dataset_mode single
```

**Comment by deepseek** [comment]
by `aligned data` you mean an inputA and outputB? inwhich each input image have it's own output image?
if so, then i have an aligned data, what should i do to?

**Comment by lmxyy** [comment]
We follow the dataset structure of [junyanz/pytorch-CycleGAN-and-pix2pix](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix). 

The aligned dataset means each input image have an explicit target output image just like pix2pix. So if you need to prepare it, just specify the dataset_mode as aligned. For example, for the edges2shoe-r dataset
```bash
python get_real_stat.py \
--dataroot database/edges2shoes-r \
--output_path real_stat/edges2shoes-r_B.npz \
--direction AtoB
```

For the unaligned dataset, which means the input image doesn't have an explicit target image, just like horse2zebra. You could use the command I mentioned above. (dataset mode single means only contains the horse images or the zebra images, since you only need to compute the FID stat for only one side)

There's also an option `--dataset_mode` option for training. Just make it consistent.

**Comment by deepseek** [comment]
i will test the aligned mode after i finish from the single mode, so keep this issue open.
but mean-while, for the [`Select the Best Model`](https://github.com/mit-han-lab/gan-compression/blob/master/docs/lite_pipeline.md#select-the-best-model-1) step, by default it chooses `latest_net_G.pth`, whil according to the `log.txt`  from the previous step [`"Once-for-all" Network Training`](https://github.com/mit-han-lab/gan-compression/blob/master/docs/lite_pipeline.md#once-for-all-network-training-1), the `fid_largest` is at `epoch 260 / 400`.
should i set it to `--restore_G_path logs/cycle_gan/horse2zebra_lite/supernet/checkpoints/260_net_G.pth`?

**Comment by lmxyy** [comment]
Of course you could. In our experiment,  we use the lastest checkpoint, which means the last one.

**Comment by deepseek** [comment]
The single mode is working great, i was able to search and find a good model within 3 hours, for horse2zebra.

Now i want to train using the `facades` dataset which is aligned, i still get the same error as before:
```
python get_real_stat.py --dataset_mode aligned --dataroot database/facades/ --output_path real_stat/facades_B.npz --direction AtoB
Traceback (most recent call last):
  File "get_real_stat.py", line 84, in <module>
    main(opt)
  File "get_real_stat.py", line 15, in main
    dataloader = create_dataloader(opt)
  File "/home/home/programs/level 2/gan-compression/data/__init__.py", line 45, in create_dataloader
    dataloader = CustomDatasetDataLoader(opt, verbose)
  File "/home/home/programs/level 2/gan-compression/data/__init__.py", line 97, in __init__
    self.dataset = dataset_class(opt)
  File "/home/home/programs/level 2/gan-compression/data/aligned_dataset.py", line 24, in __init__
    self.AB_paths = sorted(make_dataset(self.dir_AB))  # get image paths
  File "/home/home/programs/level 2/gan-compression/data/image_folder.py", line 45, in make_dataset
    assert os.path.isdir(dir) or os.path.islink(dir), '%s is not a valid directory' % dir
AssertionError: database/facades/val is not a valid directory
```

**Comment by lmxyy** [comment]
Could you please provide the directory structure of `database/facades`? 
Does the directory `database/facades/val` exist? If not, you could create it with a symlink
```
cd database/facades/
ln -s test val
```

**Comment by deepseek** [comment]
The `facades` dataset have `valA` and `valB`, how to solve


```
home@home-lnx:~/programs/level 2/gan-compression$ bash datasets/download_cyclegan_dataset.sh facades
home@home-lnx:~/programs/level 2/gan-compression$ cd database/facades/
home@home-lnx:~/programs/level 2/gan-compression/database/facades$ tree -d
.
├── testA
├── testB
├── trainA
├── trainB
├── valA -> testA
└── valB -> testB
```

**Comment by lmxyy** [comment]
Oh, you have downloaded the unaligned version of the dataset (since you used `datasets/download_cyclegan_dataset.sh`). Just download the dataset in this way
```bash
bash datasets/download_pix2pix_dataset.sh facades
```

**Comment by deepseek** [comment]
So i donwloaded the pix2pix version of `facades` as you suggested, and i was able to create the real_stat files.

Are you sure that i can train cyclegan using aligned dataset, because i get an error:
```
train.py --dataroot database/facades --dataset_mode aligned --model cycle_gan --netG resnet_9blocks --log_dir logs/cycle_gan/facades/full --real_stat_A_path real_stat/facades_A.npz --real_stat_B_path real_stat/facades_B.npz
dataset [AlignedDataset] was created
The number of training images = 400
Traceback (most recent call last):
  File "train.py", line 4, in <module>
    trainer = Trainer('train')
  File "/home/home/programs/level 2/gan-compression/trainer.py", line 51, in __init__
    model = create_model(opt)  # create a model given opt.model and other options
  File "/home/home/programs/level 2/gan-compression/models/__init__.py", line 47, in create_model
    instance = model(opt)
  File "/home/home/programs/level 2/gan-compression/models/cycle_gan_model.py", line 88, in __init__
    assert opt.dataset_mode == 'unaligned'
AssertionError
```

So i decided to change `unaligned` to `aligned` in `cycle_gan_model.py`, i am currently training and will report back later

**Comment by lmxyy** [comment]
I do not think you could change `unaligned` to `aligned` in `cycle_gan_model.py`. If you did that, you would need to modify many codes regarding to data preprocess.

The best way to launch the experiment is as follows:
* First, you download the cycleGAN version of the dataset with
```bash
bash datasets/download_cyclegan_dataset.sh facades
```
* Compute the FID statistics with `single` mode like:
```bash
python get_real_stat.py --dataroot database/facades/valB --output_path real_stat/facades_B.npz --direction AtoB --dataset_mode single
python get_real_stat.py --dataroot database/facades/valA --output_path real_stat/facades_A.npz --direction BtoA --dataset_mode single
```
* Launch your experiment like:
```bash
train.py --dataroot database/facades --dataset_mode unaligned --model cycle_gan --netG resnet_9blocks --log_dir logs/cycle_gan/facades/full --real_stat_A_path real_stat/facades_A.npz --real_stat_B_path real_stat/facades_B.npz
```

**Comment by deepseek** [comment]
i have for each input image a corresponding output image.
if i use the commands that you posted, will i be able to train using my data.
or should i switch to pix2pix?

**Comment by lmxyy** [comment]
Both are okay. It depends on which model are you going to compress.

**Comment by deepseek** [comment]
so i can't train cyclegan with aligned data?
my dataset have the resolution of 768*768 how should i prepare, train and search using pix2pix? crop options?
In my dataset, i have for each input image an explicit target output image. how can i combine the input and output images to create aligned images?

**Comment by lmxyy** [comment]
* You do can train cyclegan with aligned data, but you need modify the directory structure and preprocess like the unaligned data (like facades, the directory structures of the aligned (download with `scripts/download_pix2pix_dataset.sh`) and unaligned (download with `scripts/download_cyclegan_dataset.sh`) are different, but the content are the same).
* Yes, you could use pix2pix. Just use aligned dataset is ok. You could use (combine_A_and_B.py)[https://github.com/mit- han-lab/gan-compression/blob/master/datasets/combine_A_and_B.py] to combine your images.

**Comment by deepseek** [comment]
what about the image resolution, my images are 768*768, what should i change in preparing,training,searching...?

**Comment by lmxyy** [comment]
You could use the argument ['--load_size'](https://github.com/mit-han-lab/gan-compression/blob/7f76062ffaa357061f7e28b3f21b7eca30b5d962/options/base_options.py#L50) and ['crop_size'](https://github.com/mit-han-lab/gan-compression/blob/7f76062ffaa357061f7e28b3f21b7eca30b5d962/options/base_options.py#L51) to change the resolution during training, searching or other things.

**Comment by deepseek** [comment]
For `get_real_stat` i should change also yes?

**Comment by lmxyy** [comment]
You do not have to change it in `get_real_stat.py` since the [inception model](https://github.com/mit-han-lab/gan-compression/blob/7f76062ffaa357061f7e28b3f21b7eca30b5d962/metric/inception.py#L147) for computing FID has already rescaled the images to a fixed size. But remember to change it while training, searching and testing.

**Comment by deepseek** [comment]
How can i resume training? lets say i stopped at epoch 32 and iteration 10000.

**Comment by MuyangLi-Dawnlight** [comment]
You could use `--restore_G_path`, `--restore_D_path` to specify the checkpoints you would like to resume. 
By changing the your starting epoch and iteration with `--epoch_base` and `--iter_base`, you can go on training.

**Comment by lmxyy** [comment]
I will close the issue since it seems that your problem is not regarding to `get_real_stat.py`. If you have any other problems, feel free to open another issue.

**Comment by deepseek** [comment]
haha, i know right,
i asked you questions on how to train from scratch
Thanks!
