### ISSUE TITLE
Question about distillation

### ISSUE THREAD

**Issue by 07hyx06** [mit-han-lab/gan-compression#4]
take CycleGAN compression as an example.

the teacher generator: a MobileNet-based CycleGAN trained from scratch
the student generator: a MobileNet-based distillation CycleGAN model
the final generator: a fine-tuned sub network of student generator

Is my understanding correct?

Which means the original CycleGAN model(with normal conv) is not needed in compression algorthm?

**Comment by lmxyy** [comment]
Yes, you are correct. The CycleGAN model (with normal conv) is not needed in our compressing pipeline. But we have compared our final model with the original model (with normal conv) in our paper.

**Comment by 07hyx06** [comment]
Thx for your quick reply!
one more question: What about the behavior of the teacher generator and the student generator before NAS? I remember MobileNet can decrease 9xFLOPs on classfication. What about the MobileNet-based generator CycleGAN computation compare to the original Resnet-based one?

**Comment by lmxyy** [comment]
With the same `ngf`, the MobileNet-style generator is 5.8x smaller takes 3.1x less computation than the original resnet-based generator.

**Comment by lmxyy** [comment]
Do you have any other questions? If not, I will close the issue.

**Comment by 07hyx06** [comment]
no more. just close :D
