### ISSUE TITLE
Searching is slow.How can I continue searching when it is break.

### ISSUE THREAD

**Issue by Feywell** [mit-han-lab/gan-compression#42]
I just have one GPU. Searching is so slow. I want to run another code.
 How can I continue searching after finish another project?

>  65%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                            | 37494/57600 [40:38:20<137:38:38, 24.65s/it]MACs: 4.364G    Params: 1.987M
> {'config_str': '48_32_32_48_40_32_24_16', 'macs': 4363780096, 'fid': 68.67807846983607}
>  65%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                            | 37495/57600 [40:38:48<143:48:26, 25.75s/it]MACs: 5.282G    Params: 1.987M
> {'config_str': '48_32_32_48_40_32_16_64', 'macs': 5282070528, 'fid': 64.41984751671731}
>  65%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                            | 37496/57600 [40:39:19<152:29:44, 27.31s/it]MACs: 4.825G    Params: 1.987M
> 
Thank you!

**Comment by lmxyy** [comment]
Sorry, currently we do not support resuming the searching. But thanks for pointing out, I will add such support.

**Comment by Feywell** [comment]
Thank you for your quickly reply! Hope for new improvement.
By the way, How can I use this code to compress encode struct. I try to compress pix2pixhd now.
Do you have any advice？

**Comment by deepseek** [comment]
@lmxyy search resume is great feature to include.
@Feywell what progress did you make in implementing pix2pixhd

**Comment by lmxyy** [comment]
I see. I've included in my next released version.

**Comment by deepseek** [comment]
thanks

**Comment by lmxyy** [comment]
Hi, I've supported the searching resuming. You could use [`--restore_pkl_path`](https://github.com/mit-han-lab/gan-compression/blob/44e116cb02e35fd4d5739df9c2e7fee27f68842c/options/search_options.py#L43) for resuming the searching. 

Please note that I changed the arguments of splitting the searching space from `--split` and `--remainder` to `--num_splits` and `--split`.

**Comment by lmxyy** [comment]
> thanks
> @lmxyy is there an implementation that uses the concept of `once-for-all` on tabular data?

@deepseek Could you please open a new issue and elaborate you problems? I will close the issue.
