### ISSUE TITLE
There is a bug in tensor2im

### ISSUE THREAD

**Issue by Feywell** [mit-han-lab/gan-compression#45]
The normlize is not work, when  tensor.dim() == 4.

```
    if image_tensor.dim() == 4:
        # transform each image in the batch
        images_np = []
        for b in range(image_tensor.size(0)):
            one_image = image_tensor[b]
            one_image_np = tensor2im(one_image)
            images_np.append(one_image_np.reshape(1, *one_image_np.shape))
        images_np = np.concatenate(images_np, axis=0)
```

https://github.com/mit-han-lab/gan-compression/blob/master/utils/util.py#L69

**Comment by lmxyy** [comment]
Could you elaborate on this bug or provide some error logs? This code makes sense for me.

**Comment by Feywell** [comment]
Actually it doesn't return a error. It is not work, when normlize is False.
Because I do not use normlize to prepare my own dataset.

**Comment by lmxyy** [comment]
It doesn't make sense to me, since the `normalize` flag only affects a linear normalization. What do you mean by "it is not work"? Does your program exit normally?

**Comment by Feywell** [comment]
If you use normlize=True, this code just ok. But It will go to    https://github.com/mit-han-lab/gan-compression/blob/master/utils/util.py#L81 , when I set normlize=False.

**Comment by lmxyy** [comment]
I see. Thanks for reporting this. You could also send a pull request.
