### ISSUE TITLE
How does ‘netG_pretrained’ in MobileDistiller.py work?

### ISSUE THREAD

**Issue by Feywell** [mit-han-lab/gan-compression#46]
I feel puzzled at self.netG_pretrained in resnet_distiller.py.
It is here: https://github.com/mit-han-lab/gan-compression/blob/master/distillers/resnet_distiller.py#L94
Why it is deleted after loaded?

```
    def load_networks(self, verbose=True):
        if self.opt.restore_pretrained_G_path is not None:
            util.load_network(self.netG_pretrained, self.opt.restore_pretrained_G_path, verbose)
            load_pretrained_weight(self.opt.pretrained_netG, self.opt.student_netG,
                                   self.netG_pretrained, self.netG_student,
                                   self.opt.pretrained_ngf, self.opt.student_ngf)
            del self.netG_pretrained
        super(ResnetDistiller, self).load_networks()
```

**Comment by lmxyy** [comment]
Sorry for the confusion. `netG_pretrained` is just a pretrained network, which is used to transfer its weights to `netG_student`. The whole transferring process is somewhat like channel pruning.

**Comment by lmxyy** [comment]
We've released an improved lite pipeline, which could bypass the distillation process but could achieve almost the same results as the full pipeline. You could check the [lite_pipeline.md](https://github.com/mit-han-lab/gan-compression/blob/master/docs/lite_pipeline.md) for more details.

**Comment by Feywell** [comment]
So, I can skip the distillation process to comprocess model on my own dataset. Thanks for your reply!
