### ISSUE TITLE
Why it is getting slower and slower when training the supernets?

### ISSUE THREAD

**Issue by Feywell** [mit-han-lab/gan-compression#47]
I try to compress pix2pixhd. But I find it will cost longer time in one iter.
For example, it cost 0.4s per images in the first epoch. But it will cost 8s per image in the 5 epoch.
Do you have the same question?

**Comment by lmxyy** [comment]
Could you please provide your detailed training command? I gauss you used `--load_in_memory` in your option, which will load all the data into the memory to save the time of reading from disk and transformation. But it will take lots of memory and result in the slower and slower speed.

**Comment by Feywell** [comment]
> Could you please provide your detailed training command? I gauss you used `--load_in_memory` in your option, which will load all the data into the memory to save the time of reading from disk and transformation. But it will take lots of memory and result in the slower and slower speed.


 **Actually, I do not use this arugment**, this is my all options:

> ----------------- Options ---------------
>              aspect_ratio: 1.0                           
>                batch_size: 1                             
>                     beta1: 0.5                           
>           cityscapes_path: database/cityscapes-origin    
>                config_set: channels-64-pix2pixhd         	[default: None]
>                config_str: None                          
>                 crop_size: 256                           
>                  dataroot: None                          
>              dataset_mode: aligned                       
>            deeplabv2_path: deeplabv2_resnet101_msc-cocostuff164k-100000.pth
>                 direction: AtoB                          
>              display_freq: 1                             	[default: 400]
>                display_id: 1                             
>             display_ncols: 4                             
>              display_port: 8097                          
>            display_server: http://localhost              	[default: 10.96.107.79]
>           display_winsize: 256                           
>               distributed: False                         
>                  drn_path: drn-d-105_ms_cityscapes.pth   
>          encoder_input_nc: 3                             
>         encoder_output_nc: 16                            
>                epoch_base: 1                             
>           eval_batch_size: 1                             
>                  gan_mode: hinge                         
>        generator_input_nc: 19                            
>                   gpu_ids: 0                             
>                 init_gain: 0.02                          
>                 init_type: normal                        
>                  input_nc: 3                             
>                   isTrain: True                          	[default: None]
>                 iter_base: 1                             
>            lambda_distill: 1                             
>               lambda_feat: 100                           
>                lambda_gan: 1                             
>              lambda_recon: 100                           
>            load_in_memory: False                         
>                 load_size: 286                           
>                local_rank: 0                             
>                        lr: 0.0002                        
>            lr_decay_iters: 50                            
>                 lr_policy: linear                        
>          max_dataset_size: -1                            
>           n_blocks_global: 9                             
>            n_blocks_local: 3                             
>            n_downsample_E: 4                             
>       n_downsample_global: 4                             
>                n_layers_D: 3                             
>         n_local_enhancers: 1                             
>              n_upsample_E: 4                             
>         n_upsample_global: 5                             
>                       ndf: 128                           
>                       nef: 16                            
>                   nepochs: 100                           
>             nepochs_decay: 100                           
>                      netD: multi_scale                   	[default: n_layers]
>                   no_flip: False                         
>           no_ganFeat_loss: False                         
>                   no_html: False                         
>                  no_lsgan: False                         
>                      norm: instance                      
>                     num_D: 2                             
>               num_threads: 4                             
>               num_workers: 4                             
>           output_img_size: 592                           
>                 output_nc: 3                             
>                     phase: train                         
>                preprocess: resize_and_crop               
>                print_freq: 1                             	[default: 100]
>               random_flip: False                         
>              random_users: False                         
>           recon_loss_type: l1                            
>            restore_A_path: None                          
>            restore_O_path: None                          
>    restore_student_E_path: None                          
>    restore_student_G_path: None                          
>    restore_teacher_E_path: logs/test_train_mobile/checkpoints/latest_net_E.pth	[default: None]
>    restore_teacher_G_path: logs/test_train_mobile/checkpoints/latest_net_G.pth	[default: None]
>           save_epoch_freq: 5                             
>          save_latest_freq: 20000                         
>                      seed: 233                           
>            serial_batches: False                         
>             sort_channels: False                         
>      student_dropout_rate: 0                             
>              student_netG: super_mobile                  
>               student_ngf: 48                            
>                  supernet: resnet_mobile                 	[default: resnet]
>                table_path: datasets/table.txt            
>      teacher_dropout_rate: 0                             
>              teacher_netG: mobile                        	[default: mobile_resnet_9blocks]
>               teacher_ngf: 64                            
>           tensorboard_dir: None                          
>          train_batch_size: 2                             
>          update_html_freq: 1000                          
>            use_gabor_loss: True                          	[default: False]
>               visdom_name: main                   
>

**Comment by lmxyy** [comment]
I have no idea why the training is getting slower and slower. I do not observe such phenomenon in my experiment. I suppose you are using more and more memory for your training so the speed is getting slower.

**Comment by Feywell** [comment]
Thans for your reply!
I find my training time increase in drawing loss module. I write some code to draw loss by visdom.

**Comment by seekingdeep** [comment]
@Feywell what do you mean by "drawing loss module"
also what did you change in the code

**Comment by frytoli** [comment]
Hi all - I'm working on trying to get this working with Pix2PixHD as well. I've forked this repo and am working out of my own here: https://github.com/frytoli/gan-compression. I've added the Pix2PixHD Generator classes (global and local) from the official Pix2PixHD repo, but when I test currently I get a shape mismatch error. I'm having a hard time diagnosing where/how I can solve this issue. I see that Feywell above has defined a new config string, and I've tried that to no avail. That doesn't however mean that, that's not the solution - I may just not be doing it correctly. I'm attempting to train a "once-for-all" network with the following options (Note that the cropped/input size of my images is 512, I've added an option for no dropout layers, and I've ensured that the preprocessing option "crop" just crops the images rather than also resizing):
```
----------------- Options ---------------
             aspect_ratio: 1.0                           
               batch_size: 1                             
                    beta1: 0.5                           
calibration_load_in_memory: False                         
    calibration_meta_path: None                          
          cityscapes_path: database/cityscapes-origin    
               config_set: channels-64-pix2pix           	[default: None]
               config_str: None                          
                crop_size: 512                           	[default: 256]
                 dataroot: datasets/datasets/P2P         	[default: None]
             dataset_mode: unaligned                     	[default: aligned]
           deeplabv2_path: deeplabv2_resnet101_msc-cocostuff164k-100000.pth
                direction: BtoA                          	[default: AtoB]
          display_winsize: 256                           
                 drn_path: drn-d-105_ms_cityscapes.pth   
               epoch_base: 1                             
          eval_batch_size: 1                             
                    gamma: 0.5                           
                 gan_mode: hinge                         
                  gpu_ids: 0                             
                init_gain: 0.02                          
                init_type: normal                        
                 input_nc: 3                             
                  isTrain: True                          	[default: None]
                iter_base: 0                             
           lambda_distill: 1                             
               lambda_gan: 1                             
             lambda_recon: 100                           
           load_in_memory: False                         
                load_size: 2200                          	[default: 286]
                  log_dir: logs/supernet                 
                       lr: 0.0002                        
           lr_decay_steps: 100000                        
                lr_policy: linear                        
         max_dataset_size: -1                            
               metaA_path: None                          
               metaB_path: None                          
               n_layers_D: 3                             
                      ndf: 64                            	[default: 128]
                  nepochs: 10                            
            nepochs_decay: 30                            
                     netD: n_layers                      
                   niters: 1000000000                    
               no_dropout: True                          	[default: False]
                   no_fid: False                         
                  no_flip: False                         
                  no_mIoU: False                         
                     norm: instance                      
              num_threads: 4                             
                output_nc: 3                             
                    phase: train                         
               preprocess: crop                          	[default: resize_and_crop]
               print_freq: 100                           
           real_stat_path: stat.npz                      	[default: None]
          recon_loss_type: l1                            
           restore_A_path: None                          
           restore_D_path: None                          
           restore_O_path: None                          
   restore_student_G_path: None                          
   restore_teacher_G_path: checkpoints/pix2pix/latest_net_G.pth	[default: None]
          save_epoch_freq: 5                             
         save_latest_freq: 20000                         
        scheduler_counter: epoch                         
                     seed: 233                           
           serial_batches: False                         
     student_dropout_rate: 0                             
             student_netG: super_mobile_resnet_9blocks   
              student_ngf: 64                            	[default: 48]
                 supernet: resnet                        
               table_path: datasets/val_table.txt        
     teacher_dropout_rate: 0                             
             teacher_netG: pix2pixhd                     	[default: mobile_resnet_9blocks]
              teacher_ngf: 64                            
          tensorboard_dir: None 
```

And I receive this error:
```
Load network at checkpoints/pix2pix/latest_net_G.pth
Traceback (most recent call last):
  File "train_supernet.py", line 4, in <module>
    trainer = Trainer('supernet')
  File "/content/gan-compression/trainer.py", line 53, in __init__
    model.setup(opt)  # regular setup: load and print networks; create schedulers
  File "/content/gan-compression/distillers/base_resnet_distiller.py", line 124, in setup
    super(BaseResnetDistiller, self).setup(opt, verbose)
  File "/content/gan-compression/models/base_model.py", line 89, in setup
    self.load_networks(verbose=verbose)
  File "/content/gan-compression/supernets/resnet_supernet.py", line 162, in load_networks
    super(ResnetSupernet, self).load_networks()
  File "/content/gan-compression/distillers/base_resnet_distiller.py", line 208, in load_networks
    util.load_network(self.netG_teacher, self.opt.restore_teacher_G_path, verbose)
  File "/content/gan-compression/utils/util.py", line 142, in load_network
    net.load_state_dict(weights, strict=False)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1483, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for GlobalGenerator:
	size mismatch for model.16.conv_block.1.weight: copying a param with shape torch.Size([1024, 1024, 3, 3]) from checkpoint, the shape in current model is torch.Size([512, 512, 3, 3]).
	size mismatch for model.16.conv_block.1.bias: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for model.17.conv_block.1.weight: copying a param with shape torch.Size([1024, 1024, 3, 3]) from checkpoint, the shape in current model is torch.Size([512, 512, 3, 3]).
	size mismatch for model.17.conv_block.1.bias: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for model.18.conv_block.1.weight: copying a param with shape torch.Size([1024, 1024, 3, 3]) from checkpoint, the shape in current model is torch.Size([512, 512, 3, 3]).
	size mismatch for model.18.conv_block.1.bias: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for model.19.conv_block.1.weight: copying a param with shape torch.Size([1024, 1024, 3, 3]) from checkpoint, the shape in current model is torch.Size([512, 512, 3, 3]).
	size mismatch for model.19.conv_block.1.bias: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for model.20.conv_block.1.weight: copying a param with shape torch.Size([1024, 1024, 3, 3]) from checkpoint, the shape in current model is torch.Size([512, 512, 3, 3]).
	size mismatch for model.20.conv_block.1.bias: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for model.21.conv_block.1.weight: copying a param with shape torch.Size([1024, 1024, 3, 3]) from checkpoint, the shape in current model is torch.Size([512, 512, 3, 3]).
	size mismatch for model.21.conv_block.1.bias: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for model.25.weight: copying a param with shape torch.Size([1024, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 128, 3, 3]).
	size mismatch for model.25.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for model.28.weight: copying a param with shape torch.Size([512, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 64, 3, 3]).
	size mismatch for model.28.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
```

Any help is greatly appreciated - thank you in advance!

**Comment by frytoli** [comment]
@Feywell @seekingdeep - hey there! I'm looking at implementing this for Pix2PixHD as well. Were either of you able to get this working? Do you have any pointers or code? Thanks in advance.
