### ISSUE TITLE
Questions about resnet_supernet in pix2pix_model.

### ISSUE THREAD

**Issue by pengfeiZhao1993** [mit-han-lab/gan-compression#49]
1.          if **getattr(opt, 'sort_channels', False)** and opt.restore_student_G_path is not None:  # line 74 for base_resnet_distiller.py
          For "**getattr(opt, 'sort_channels', False)**", I check the definition of the function "getattr", it used to be the format of "getattr(object, name, default=None)", and when setting this default papram to "False" or "True", it won't affect the function output, this function just return the value of **opt.sort_channels** . 

2.    **I want to know do I need to sort channels before OFA**, that is, setting sort_channels = True. cuz I notice the role of "netG_student_tmp" in supernet training, sorting channels before transfering pretrained weights to student_netG.

**Comment by lmxyy** [comment]
I just want to make sure when the `opt` doesn't have attribute `sort_channels`, the return value is `False`. 
But as a matter of fact, we do not use the sort channels before OFA. This is the legacy part of my experiment codes, which I forgot to remove. Sorry for the confusion.

**Comment by pengfeiZhao1993** [comment]
Wow, so quick feedback. Thank you.
I got it.  I didn't use the getattr before, LOL.
