### ISSUE TITLE
About channel pruning

### ISSUE THREAD

**Issue by hhuyujie** [mit-han-lab/gan-compression#5]
Could you tell me which document can let me understand the process of channel pruning?

**Comment by lmxyy** [comment]
Do you mean the process of "once-for-all" network training?

**Comment by huangqiu15444** [comment]
I got the same problem.

**Comment by lmxyy** [comment]
> I got the same problem.

Could you please specify which part of our paper you do not quite understand?

**Comment by junyanz** [comment]
See Sec 3.2 and 3.3 in the original [paper](https://arxiv.org/abs/2003.08936).

**Comment by huangqiu15444** [comment]
Thanks for your reply!
I just want to know that if I got a teacher network how doo I generate the student “once-for-all” generato and where is the code I can use?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Muyang Li"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月25日(星期一) 晚上10:07
收件人:&nbsp;"mit-han-lab/gan-compression"<gan-compression@noreply.github.com&gt;;
抄送:&nbsp;" "<154443651@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [mit-han-lab/gan-compression] About channel pruning (#5)





  
I got the same problem.
  
Could you please specify which part of our paper you do not quite understand?
