### ISSUE TITLE
question regarding pix2pixHD

### ISSUE THREAD

**Issue by dearkafka** [mit-han-lab/gan-compression#51]
Hi! Thank you all for the tremendous and awesome work.

I want to ask you what would be your recommendations regarding incorporating pix2pixHD?

I've done almost all the necessary steps, but I'm interested in your advice on supernet. pix2pixHD has the same amount of blocks as pix2pix, however, the dimensionality of connecting layers (mapping layers) differs. How would you propose to modify resnet-9blocks for that? or maybe you have better faith in another architecture?

**Comment by lmxyy** [comment]
It is okay to follow the original Pix2pixHD generator architecture. In my opinion, you could use the "once-for-all" trying to finelly reduce the channel width of Pix2pixHD. You may need to support search space in the Pix2pixHD supernet modules. Currently, we have adopted the evolution search algorithm, which is much more efficient than the previous search algorithm, so you do not have to worry about the size of the search space. 
I think you could try our SPADE model, which is reported to be more efficient in their paper, and we already have some results on SPADE. I do not know the capacity and the redundancy of Pix2pixHD, so I could not predict your results. If your question is more detailed, I think I may give you more feasible advice.
