### ISSUE TITLE
real_stats for COCO

### ISSUE THREAD

**Issue by deJQK** [mit-han-lab/gan-compression#52]
Could you share the real_stats for the COCO data? It is not downloadable, and running the get_real_stat.py file for the coco data returns error:
`python get_real_stat.py --dataroot database/coco_stuff --output_path real_stat/coco_A.npz --direction BtoA --dataset_mode coco`

> RuntimeError: Sizes of tensors must match except in dimension 0. Got 424 and 640 in dimension 2 (The offending index is 1)

Thanks.

**Comment by MuyangLi-Dawnlight** [comment]
Thanks for the notification. I have uploaded our real_stat file for COCO. You could download it with
```bash
bash datasets/download_real_stat.sh coco A
```
I will check why your command could not work. It may be a data issue.

**Comment by lmxyy** [comment]
Thanks for the notification. I have uploaded our real_stat file for COCO. You could download it with
```bash
bash datasets/download_real_stat.sh coco A
```
I will check why your command could not work. It may be a data issue.

**Comment by lmxyy** [comment]
I am wondering how you preprocess the COCO dataset? Is it the same as [SPADE](https://github.com/NVlabs/SPADE). I find that your command is workable.

**Comment by deJQK** [comment]
Thanks for the reply. I was using the same preprocessing in SPADE. The code can run correctly for each image data, but raise error at [this line](https://github.com/mit-han-lab/gan-compression/blob/master/get_real_stat.py#L31). I downloaded an early version when COCO results are not included, but I modified the necessary part in the data and metric code for COCO based on the current version.

**Comment by lmxyy** [comment]
Oh, I think I know the reason of your error. Since the input images of COCO-Stuff are of multiple resolutions, you could not directly concanate them together. All you need to do is just to resize the images with this additional option `--preprocess resize_and_crop` (default is `none`).

**Comment by deJQK** [comment]
Hi @lmxyy , thanks a lot for your kind help.
