### ISSUE TITLE
bug in evolution.py 

### ISSUE THREAD

**Issue by artyomnaz** [mit-han-lab/gan-compression#53]
Hello! Thank you all for your amazing work!

So, I think that your code in _evolution.py_ might has an error. 
Why did you take _sample2['channels'][1]]_ in line 124? Maybe you will consider _sample2['channels'][i]]_?

line 124: _new_sample['channels'][i] = random.choice([sample1['channels'][i], sample2['channels'][1]])_

**Comment by lmxyy** [comment]
Oh yes, you are right. Thanks for pointing it out!
