### ISSUE TITLE
What's the differences among Full Pipeline (Paper), Full Pipeline (Retrained) and Lite Pipeline?

### ISSUE THREAD

**Issue by zkchen95** [mit-han-lab/gan-compression#56]
What's the differences among these three pipelines?

**Comment by lmxyy** [comment]
The models of **Full Pipeline (Paper)** are the models we report in our [paper](https://arxiv.org/abs/2003.08936). They are trained with our legacy code. Models in **Full Pipeline (Retrained)** are the models we compressed our this released with this repo to make sure our results are reproducible. To further simplify and speed up the compression procedure, we propose an improved lite pipeline, which could produce comparable results as GAN Compression but with a much simpler and faster pipeline. The models of **Lite Pipeline** are compressed with this improved pipeline. Please refer to the [tutorial](https://github.com/mit-han-lab/gan-compression/blob/master/docs/lite_pipeline.md) for more details.

**Comment by zkchen95** [comment]
> The models of **Full Pipeline (Paper)** are the models we report in our [paper](https://arxiv.org/abs/2003.08936). They are trained with our legacy code. Models in **Full Pipeline (Retrained)** are the models we compressed our this released with this repo to make sure our results are reproducible. To further simplify and speed up the compression procedure, we propose an improved lite pipeline, which could produce comparable results as GAN Compression but with a much simpler and faster pipeline. The models of **Lite Pipeline** are compressed with this improved pipeline. Please refer to the [tutorial](https://github.com/mit-han-lab/gan-compression/blob/master/docs/lite_pipeline.md) for more details.

Does **Full Pipeline (Retrained)**  means that you retrained the compressed model **from scratch** according the searched channels configuration ?

**Comment by lmxyy** [comment]
It means I recompressed the models from scratch strictly according to this [tutorial](https://github.com/mit-han-lab/gan-compression/blob/master/docs/full_pipeline.md).
