### ISSUE TITLE
can it go below 1.6G MACs?

### ISSUE THREAD

**Issue by seekingdeep** [mit-han-lab/gan-compression#60]
it seems that macs: 1660289024 is the minimum computational cost
@lmxyy is it possible to achieve less than 1.6G MACs?

**Comment by lmxyy** [comment]
Hi! You could modify the search space in [resnet_configs.py](https://github.com/mit-han-lab/gan-compression/blob/master/configs/resnet_configs.py). Specifically, you need to include the channel number of 8, such as
```python
if config_name == 'channels-64-cycleGAN':
        return ChannelConfigs(n_channels=[[64, 48, 32, 24, 16, 8], [64, 48, 32, 24, 16, 8], [64, 48, 32, 24, 16, 8],
                                          [64, 48, 32, 24, 16, 8], [64, 48, 32, 24, 16, 8], [64, 48, 32, 24, 16, 8],
                                          [64, 48, 32, 24, 16, 8], [64, 48, 32, 24, 16, 8]])
```
But we think $8$ may be too small for the CycleGAN model.

**Comment by seekingdeep** [comment]
@lmxyy thanks
