### ISSUE TITLE
2 images as input to pix2pix

### ISSUE THREAD

**Issue by aomv** [mit-han-lab/gan-compression#63]
Hi,

 I would like to train pix2pix with 2 input images instead of only 1. I’ve seen on regular pix2pix codebase this could be achieved with the aligned_dataset.py script and adding an adoption to concatenate the 2 images into a single image with 6 channels.
 How could I go about modifying your codebase to achieve the same effect?

thank you

**Comment by lmxyy** [comment]
I think the process is very similar. You would need to do is just adapt the [aligned_dataset](https://github.com/mit-han-lab/gan-compression/blob/master/data/aligned_dataset.py) to what you want, and set the `--input_nc` to 6 instead of 3.

**Comment by aomv** [comment]
Thanks... yes I’ve done that now but I got an error after the first epoch as it tries to save an image with 6 channels 😅

so I think I’ll have to disable saving input images or split the channels before saving...

![Uploading B4FA26F7-094E-4DB9-987F-40FA66B89D7E.jpeg…]()
