### ISSUE TITLE
Is cross-over  ignored in evolution-search？

### ISSUE THREAD

**Issue by insomnia250** [mit-han-lab/gan-compression#64]
Thanks for sharing! 
I have a question about the evolution-search.
According to [this line](https://github.com/mit-han-lab/gan-compression/blob/master/evolution_search.py#L253), only childs generated by mutation will be add to population. The cross-over ones are not. Do I misunderstand or is it by design or is a bug?

**Comment by lmxyy** [comment]
Yes. This is a bug, thanks for pointing it out.
