### ISSUE TITLE
No such file or directory in demo code (scripts/cycle_gan/horse2zebra_fast/evolution_search.sh)

### ISSUE THREAD

**Issue by YSL0226** [mit-han-lab/gan-compression#73]
I followed Fast GAN Compression Training Tutorial to download the dataset and run scripts/cycle_gan/horse2zebra_fast/evolution_search.sh, but it showed "FileNotFoundError: [Errno 2] No such file or directory: 'database/horse2zebra/valA/n02381460_1019.jpg'".
I checked the valA folder, 'n02381460_1019.jpg' is not in the folder.
Moreover, there are several images are not in the folder. Is it because wrong folder path? 
How do I fix it?

After this error pop out, I tried to change dataroot with '--root database/horse2zebra/trainA/', but dataroot cannot be changed.

**Comment by lmxyy** [comment]
Sorry. It should be `--root database/horse2zebra/trainA`. To prevent the search overfits to the test set, I split the whole train set into a train1 and train2 set. Train1 set is for training and train2 set is for search, and this is controlled by the argument `--meta_path`.

**Comment by YSL0226** [comment]
It work well. Thank you!
