### ISSUE TITLE
Instance Segmentation using pix2pix

### ISSUE THREAD

**Issue by seekingdeep** [mit-han-lab/gan-compression#74]
@lmxyy @junyanz Hi there,

i am trying to use pix2pix to train an instance segmentation model,
My input images that are used in training are `256*256` crops of my original `1024*1024` images.

The **issue** is that:
- if using `256*256` crops in training, the model is not converging and the `fid` is somewhat bad.
Because the `256*256` crops are too small, and the information of the "big picture" is somewhat lost.

- When trying to using the original `1024*1024`, it requires high memory when running `get_real_stat.py`.

Possible solution:
[# 44](https://github.com/mit-han-lab/gan-compression/issues/44#issuecomment-687620709) is to store the image tensor on the disk and then modify the dataloader to restore the tensors from the disk.

i think using the HD original images `1024*1024` in training should get better results,
Waiting for your reply

iteration 185000, Prediction:
![predition](https://user-images.githubusercontent.com/71519088/112889468-58176600-90de-11eb-9318-fd30fdf578ef.png)

Groundtruth:
![10013](https://user-images.githubusercontent.com/71519088/112889529-69607280-90de-11eb-8697-369525cfb05a.png)

**Comment by lmxyy** [comment]
I think you could try the original resolution. Storing the image tensor on the disk and then modify the data loader to restore the tensors from the disk is a good solution when running the `get_real_stat.py` is a good solution and deserves a trial.

**Comment by seekingdeep** [comment]
also, can i choose to disable using `real_stat`?
