### ISSUE TITLE
default setting for opt.phase in evolution_options.py and search_options.py in options directory

### ISSUE THREAD

**Issue by kminsoo** [mit-han-lab/gan-compression#78]
Thank you for sharing your code. 

Until now, I have read your code only for pix2pix Model Compression part, and I would like to ask you about the part as below.
Should the default value for opt.phase be 'train' not 'val' as written in your code for pix2pix model compression in evolution_options.py and search_options.py in options directory?
Since you set to the real_stat_path real_stat/edges2shoes-4_subtrain_B.npz, I think that the opt.phase should be set to 'train'.

**Comment by lmxyy** [comment]
Yes, it should be `train`. I miss it. Thank you very much for point it out! The detailed reason is specified in #73.
