### ISSUE TITLE
About config

### ISSUE THREAD

**Issue by vanduong0504** [mit-han-lab/gan-compression#79]
Can you explain for me about ` --config_str` means?
```
if config_name == 'channels-48':        
     return ChannelConfigs(n_channels=[[48, 32], [48, 32], [48, 40, 32],
                                       [48, 40, 32], [48, 40, 32], [48, 40, 32],
                                       [48, 32, 24, 16], [48, 32, 24, 16]])
```
And the `config_str = 16_16_32_16_32_32_16_16` when search means?
I guess that means 8 layers in `Resnet9block`  you said in the paper? If true why 8 instead of 9? Sorry for reopen many times.
Thank you.

**Comment by lmxyy** [comment]
The layer number of the upsampling and downsampling layers is also included in this configuration. Specifically, the first 3 are for the downsampling layers. The middle 3 are for the Resblocks. The last 2 are for the upsampling layers.
