### ISSUE TITLE
It can be continued to train?

### ISSUE THREAD

**Issue by PatrickHaopc** [mit-han-lab/gan-compression#82]
It occurred to power off when I was training the MobileNet Teacher Model, can I continue to train from where it breaked off ?

**Comment by lmxyy** [comment]
Of course. You could use `restore_G_path` and `restore_D_path` to restore the generator and discriminator, and use `restore_O_path` to restore your optimizer. Also remember to change the `epoch_base` and `iter_base` to the correct value.
