### ISSUE TITLE
Cann't download one of pretrained model in the Tutorial

### ISSUE THREAD

**Issue by kasim0226** [mit-han-lab/gan-compression#83]
Hi
I can not download the pretrained model from the following script. However, other pretrained model I can downlead them. 
Can you take a look? Thanks
python scripts/download_model.py --model cycle_gan --task horse2zebra --stage distill

**Comment by lmxyy** [comment]
I think it is downloadable now. Original GAN Compression is deprecated, you could refer to our [Fast GAN Compression](https://github.com/mit-han-lab/gan-compression/blob/master/docs/tutorials/fast_gan_compression.md) tutorial.
