### ISSUE TITLE
Super spectral normalization

### ISSUE THREAD

**Issue by sunpeng1996** [mit-han-lab/gan-compression#84]
hi, I have a question.
I notice that you have achieved the superconv and SuperSynchronizedBatchNorm2d, but how can I achieve the Super spectral normalization? Do you have any suggestions?

**Comment by lmxyy** [comment]
It is somewhat hard to convert the spectral normalization to the super one. In our experiments, we observe that removing the spectral normalization also performs the same. So you could just implement the normal super normalization without spectral norm.
