### ISSUE TITLE
where is bash scripts/cycle_gan/horse2zebra/search.sh?

### ISSUE THREAD

**Issue by gewenchao** [mit-han-lab/gan-compression#92]

**Comment by lmxyy** [comment]
I think it is [there](https://github.com/mit-han-lab/gan-compression/blob/master/scripts/cycle_gan/horse2zebra/search.sh). For *Fast GAN Compression*, we directly use the evolutionary search, whose script is [this](https://github.com/mit-han-lab/gan-compression/blob/master/scripts/cycle_gan/horse2zebra_fast/evolution_search.sh).
