### ISSUE TITLE
about SuperConv2d

### ISSUE THREAD

**Issue by YangGangZhiQi** [mit-han-lab/gan-compression#99]
Hi， thanks for your great works! When  reading the source code, I could not understand the role of SuperConv2d  class. 
![superConv2d问题](https://user-images.githubusercontent.com/87355944/163743891-5bb418b7-3b1a-4f3c-9599-b35d0e5ff169.png)
It sames like that output weights and bias is just the result of truncated channels of input weights and bias. What's the goals of this process. I would appreciate it if someone could help me.

**Comment by lmxyy** [comment]
This is because we are doing the channel pruning. `config` specifies how many output channels should be preserved after the pruning. In our codebase, we select the first `out_nc` channels to preserve, so that's why it looks like a truncation.

**Comment by YangGangZhiQi** [comment]
Thanks for your quick reply. Get it!
I have another question about ChannelConfigs.
![channelConfig](https://user-images.githubusercontent.com/87355944/163771897-ace9713e-2519-4643-9a1f-57f2ebe1c87f.png)
When reading your code, I could not find other code to use config=self.configs.sample().
In self.forward() method,  there is just an asignment(self.netG_student.configs = config)， I  could not find other code to use self.netG_student.configs。So what's the role of self.netG_student.configs ? I would appreciate it if someone could help it.

**Comment by YangGangZhiQi** [comment]
Thanks for your quick reply! Got it !
